### PR TITLE
Tweaks to prevent 404

### PR DESCRIPTION
**Pull request by edbordin**
I just tried using v0.3.3 and for some reason it didn't work in a clean env - I got the same errors about "invalid zip file" which were caused by the whl file not downloading. The tweaks to the request headers in this PR seemed to resolve the error by stopping the server responding with 404 - hopefully the CI tests start passing now!

edit: nope, that made it worse. probably because I messed up the headers when it builds the cache. Will have another look later

### CODE REVIEW

**Comment by edbordin** [comment]
I tested this out in a set of virtual envs on my machine (covering all the versions in the CI matrix) and this patch appeared to work across the board. Not sure why it's failing in the CI env...

**Comment by lepisma** [comment]
CI reports are weird. Even the successful builds have that `BadZipFile` error (maybe right exit code is not getting through).

**Comment by edbordin** [comment]
Yeah, looks like the exit code isn't correct. I've been trying to use the patched version today and still getting intermittent failures, but it could just be my connection being flaky today...

**Comment by lepisma** [comment]
A question: Do people use this (`pipwin` and gohlke's source) for windows? I was wondering this becaue  there are better and well maintained binary package repositories (the `conda` ecosystem).

**Comment by edbordin** [comment]
I've personally been using gohlke's packages because tensorflow doesn't officially support anaconda. Also because our production env is vanilla CPython on Linux so this seemed closer. Perhaps I'm just making my life harder than it needs to be though...

**Pull request merged**
